version: '3.9'

services:
    db:
        image: postgres:16.3-alpine
        restart: always
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run python manage.py runserver 0.0.0.0:8000
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        depends_on:
            - db

volumes:
    postgres-data:
